name: Build Kernel A03 Core
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Install Toolchain & Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y bc build-essential bison flex libssl-dev libelf-dev \
          libncurses5 libncurses5-dev lib32z1 libc6-i386 python2
          
          git clone --depth=1 https://github.com/mvaisakh/gcc-arm64 gcc64
          git clone --depth=1 https://github.com/crdroidandroid/android_prebuilts_clang_host_linux-x86_clang-6443078 clang

      - name: Build Kernel
        run: |
          # DISINI GUE GAK ASUMSI LAGI: Cari file aslinya ada di folder mana
          GCC_BIN=$(find $(pwd)/gcc64 -name "aarch64-linux-android-gcc" -type f -exec dirname {} + | head -n 1)
          CLANG_BIN=$(find $(pwd)/clang -name "clang" -type f -exec dirname {} + | head -n 1)
          
          # Masukkan hasil temuan ke PATH
          export PATH=$CLANG_BIN:$GCC_BIN:$PATH
          
          # Cek di log biar lu liat sendiri bener apa nggak lokasinya
          echo "LOKASI GCC: $GCC_BIN"
          echo "LOKASI CLANG: $CLANG_BIN"
          
          export ARCH=arm64
          export CROSS_COMPILE=aarch64-linux-android-
          export CLANG_TRIPLE=aarch64-linux-gnu-

          make O=out clean
          make O=out mrproper

          # Konfigurasi
          make O=out CC=clang CROSS_COMPILE=aarch64-linux-android- a3core_eur_open_defconfig

          # Compile (Bypass stack protector biar gak rewel)
          make -j$(nproc --all) O=out \
            CC=clang \
            CROSS_COMPILE=aarch64-linux-android- \
            CLANG_TRIPLE=aarch64-linux-gnu- \
            LD=ld.lld \
            CONFIG_CC_STACKPROTECTOR_STRONG=n \
            BSP_BUILD_DT_OVERLAY=y

      - name: Upload Kernel
        uses: actions/upload-artifact@v4
        with:
          name: Kernel-Image
          path: out/arch/arm64/boot/Image
