name: Build Kernel A03 Core
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Install Toolchain & Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y bc build-essential bison flex libssl-dev libelf-dev
          
          # 1. Download GCC 4.9
          git clone --depth=1 https://github.com/mvaisakh/gcc-arm64 gcc64
          
          # 2. Download Clang 
          git clone --depth=1 https://github.com/crdroidandroid/android_prebuilts_clang_host_linux-x86_clang-6443078 clang

      - name: Build Kernel
        run: |
          # 1. Setup Path
          export PATH=$(pwd)/clang/bin:$(pwd)/gcc64/bin:$PATH
          
          # 2. Setup Variables (Disesuaikan dengan Toolchain mvaisakh)
          export ARCH=arm64
          export CROSS_COMPILE=aarch64-linux-gnu-
          export CROSS_COMPILE_ARM32=arm-linux-gnueabi-
          export CLANG_TRIPLE=aarch64-linux-gnu-
          
          # Tambahan biar Clang tau di mana folder GCC-nya
          export KBUILD_BUILD_USER=Xsans
          export KBUILD_BUILD_HOST=GithubActions

          # 3. Bersihkan sisa gagal tadi
          make O=out clean
          make O=out mrproper

          # 4. Konfigurasi
          make O=out CC=clang CLANG_TRIPLE=aarch64-linux-gnu- CROSS_COMPILE=aarch64-linux-gnu- a3core_eur_open_defconfig

          # 5. Compile (Pake semua "senjata" LLVM biar gak rewel)
          make -j$(nproc --all) O=out \
            CC=clang \
            LD=ld.lld \
            AR=llvm-ar \
            NM=llvm-nm \
            OBJCOPY=llvm-objcopy \
            OBJDUMP=llvm-objdump \
            STRIP=llvm-strip \
            CLANG_TRIPLE=aarch64-linux-gnu- \
            CROSS_COMPILE=aarch64-linux-gnu- \
            BSP_BUILD_DT_OVERLAY=y

          # 1. Konfigurasi
          make O=out CC=clang LD=ld.lld a3core_eur_open_defconfig

          # 2. Compile
          make -j$(nproc --all) O=out CC=clang LD=ld.lld BSP_BUILD_DT_OVERLAY=y

      - name: Upload Kernel
        uses: actions/upload-artifact@v4
        with:
          name: Kernel-A03Core-Image
          path: out/arch/arm64/boot/Image
